Add resource type to execution completed
trento-project/contracts pull request #45
Opened 2023-06-07 16:31 UTC by nelsonkopliku

Adds a `ResourceType` definition that allows to identify the resource for which a check execution is being run.

Currently `host` and `cluster` are made available. As we add support for more checks scopes (ie: sap systems) we'll add more definitions.

Added the resource type to `ExecutionCompleted` by now. As we proceed with the implementation of host checks we will update other needed protos, for instance `ExecutionRequested`.

2023-06-07 16:35 UTC, CDimonaco requested changes

2023-06-07 16:35 UTC, CDimonaco commented on protobuf/resource_type.proto
> +    UNKNOWN = 0;
My bad today, I said unknown but if we want to stick to the convention, use unspecified https://protobuf.dev/programming-guides/dos-donts/#do-include-an-unspecified-value-in-an-enum

2023-06-08 06:30 UTC, arbulu89 submitted a review, later dismissed
Perfect

> Added the resource type to ExecutionCompleted by now. As we proceed with the implementation of host checks we will update other needed protos, for instance ExecutionRequested.

Alright!

2023-06-08 06:38 UTC, arbulu89 reviewed
Hey @nelsonkopliku ,
With the new `0.11.0` version, checking the changelog, I have noticed that they have deprecated the `new/new!` functions. https://github.com/elixir-protobuf/protobuf/blob/main/CHANGELOG.md#deprecations
I think this will be an issue, as we use them in our mapping.
Could you have a look?
Maybe worth to defer to upgrade of version if that's the case...

2023-06-08 08:26 UTC, arbulu89 approved these changes
@nelsonkopliku Ok!
Please track the debt
(I wouldn't add these changes in the work you will do. I would create individual PRs to fix this so we have the PR really visible and documented)

2023-06-08 08:39 UTC, dottorblaster approved these changes
@arbulu89 you're right, let's tackle this as soon as possible when we touch Wanda and the Web. I don't like too much the new `.struct()` but it is what it is :smile:

2023-06-08 09:51 UTC, CDimonaco approved these changes

2023-06-08 10:31 UTC, merged